In [ ]:
import numpy as np

In [ ]:
array = np.array([1,2,3,4,5])
array

array([1, 2, 3, 4, 5])

In [ ]:
shape = array.shape
shape

(5,)

Reshape 1d to 2d

In [ ]:
array1 = np.arange(6)
array1.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
array2 = np.array([6,7,8,9,10])
array2

array([ 6,  7,  8,  9, 10])

Concatenate arrays

In [ ]:
final_arr = np.concatenate((array1,array2),axis=0)
final_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Calculate mean, standard deviation and median

In [ ]:
final_arr.mean()

5.0

In [ ]:
final_arr.std()

3.1622776601683795

In [ ]:
import statistics as st
st.median(final_arr)

5